config/routes.rb
Rails.application.routes.draw do
  # Root URL of the app
  root to: "static_pages#index"

  # Devise routes
  devise_for :users
  
  # By using the format false option, we restrict the non-api part of the site to only serving html
  scope :format => false do
    resources :cars, defaults: { format: :html}
  end
  
  # By using the format false option, we restrict the api to only serving json
  scope :api, :format => false do
    resources :cars, defaults: { format: :json}
  end

  # Redirect everything not explicitly defined to reactjs
  get "*path" => "static_pages#index"
end

app/models/car.rb
class Car < ActiveRecord::Base
  validates :name, presence: true, allow_nil: false
  validates :description, presence: true, allow_nil: false
  validates :price,  presence: true, allow_nil: false

  # Concatenates and returns the name and the price of the current model with some minor formatting
  def name_and_price
    [name, "$" + price.to_s].join " - "
  end

end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Returns all cars. Simply for demonstration purpsoses of using mocks and stubs
  def all_cars
    @cars = Car.all()
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:name, :description, :price)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  # Not using the before authenticate! action as it doesn't play nicely with rspec. So instead just write our own... simple.
  # before_filter :require_login

  def index
    @login_status = "Logged In User"
    render "index"
  end

  def require_login
    unless user_signed_in?
      @login_status = "Not Logged In User"
      redirect_to url_for :controller => "devise/sessions", :action => "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
  # Concatenates two strings. Arguably not even necessary as the function name is obvious. But a good habit to comment.
  #
  # * *Args*    :
  #   - +x+ -> the string that will appear first.
  #   - +y+ -> the string that will appeor second
  # * *Returns* :
  #   - the concatenated string
  def concat_strings(x, y)
    return [x, y].join " "
  end

  # Returns details about a car as a string. This may not be in the right place, but this is here primarily
  # for educational purposes on mocking.
  #
  # * *Args*    :
  #   - +car+ -> A car
  # * *Returns* :
  #   - the final string
  def car_details(car)
    unless(car.nil?)
      return car.name + " - " + car.description + " - $" + car.price.to_s
    else
      return "No details present"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
Cars

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @car.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @car.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @car.price %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExampleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :header_scripts %>

  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>


<%= yield %>
<%= debug(params) if Rails.env.development? %>
<%= yield :footer_scripts %>
</body>
</html>

app/views/static_pages/index.html.erb
<% content_for :footer_scripts do %>
  <%= javascript_include_tag "react-bundle" %>
<% end %>
<div id="react-app"></div>